#!/bin/bash

#SBATCH --array=0-43  # Replace N with your loop size
#SBATCH --account=coenv
#SBATCH --cpus-per-task=2 #number of CPUs
#SBATCH --mem=30GB #RAM
#SBATCH --partition='cpu-g2'
#SBATCH --time=48:00:00 #time limit 32 hour
#SBATCH -J dciw
#SBATCH --output=logs/iws_time_%a.out
#SBATCH --error=logs/iws_time_%a.err

# The $SLURM_ARRAY_TASK_ID will be the loop index
cd simulation/internal_waves
module load matlab
matlab -nodisplay -nodesktop -r "KB2OOI_time_func($SLURM_ARRAY_TASK_ID); exit"