#!/bin/bash
#SBATCH --job-name=pe_monthly
#SBATCH --output=logs/pe_monthly_single.out
#SBATCH --error=logs/pe_monthly_single.err
#SBATCH --time=10:00:00
#SBATCH --mem=500G
#SBATCH --cpus-per-task=100 #number of CPUs
#SBATCH --account=coenv
#SBATCH --partition=cpu-g2

# Make sure logs directory exists
mkdir -p logs

node="HYS14"
month=12

echo "Running with node=${node}, month=${month}"
python simulation/pe_simulation/monthly_arrivals.py --node "${node}" --month "${month}"