#!/bin/bash

#SBATCH --job-name=pe_run

#SBATCH --account=coenv
#SBATCH --cpus-per-task=90 #number of CPUs
#SBATCH --mem=600GB #RAM
#SBATCH --partition=cpu-g2
#SBATCH --time=72:00:00 #time limit 8 hours

#SBATCH --export=all
#SBATCH --output=logs/time_front.out # where STDOUT goes
#SBATCH --error=logs/time_front.err # where STDERR goes

# run simulation
eval "$(conda shell.bash hook)"
conda activate kb
python simulation/pe_simulation/time_fronts.py